# Generated by Django 4.2.1 on 2023-06-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Tags'},
        ),
    ]
