# Generated by Django 4.2.1 on 2023-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_ingredients_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.SlugField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
