# Generated by Django 4.2.1 on 2023-06-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_tags_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='slug',
            field=models.SlugField(default=1, max_length=90, unique=True),
            preserve_default=False,
        ),
    ]
