# Generated by Django 4.2.1 on 2023-06-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_ingredients_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='measurment_unit',
            new_name='measurement_unit',
        ),
    ]
