# Generated by Django 4.2.1 on 2023-06-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_rename_measurment_unit_ingredients_measurement_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='amount',
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
