# Generated by Django 4.2.1 on 2023-06-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_favorite_favorite_unique_user_recipe_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
