# Generated by Django 4.2.1 on 2023-06-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_delete_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipetags',
            name='unique tag',
        ),
        migrations.AddConstraint(
            model_name='recipetags',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='unique_tag'),
        ),
    ]
