# Generated by Django 4.2.1 on 2023-06-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_recipeingredients_unique_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='images/'),
        ),
    ]
