# Generated by Django 4.2.1 on 2023-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='slug',
            field=models.SlugField(max_length=90),
        ),
    ]
