# Generated by Django 4.2.1 on 2023-06-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_follow_follow_unique_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_subscribed',
        ),
    ]
