# Generated by Django 4.2.1 on 2023-06-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0002_alter_shopcart_recipe_alter_shopcart_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe'),
        ),
    ]
