# Generated by Django 4.2.1 on 2023-06-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0003_shopcart_unique_user_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shopcart',
            name='unique_user_recipe',
        ),
    ]
