# Generated by Django 4.2.1 on 2023-06-05 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_remove_ingredients_amount_recipeingredients_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopcart', '0004_remove_shopcart_unique_user_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopcart', to='recipe.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='shopcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe'),
        ),
    ]
